name: v$(Date:yyyyMMdd)$(Rev:rr)
pr:
  autoCancel: false
  branches:
    include:
    - master 
trigger: 
  branches:
    include:
    - master
resources:
  repositories:
  - repository: Maven
    type: GitHub 
    endpoint: KIRTHISHKT
    name: KIRTHISHKT/Maven 

stages:

- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Write your commands here
          
          echo Hello world