name: v$(Date:yyyyMMdd)$(Rev:rr)
pr:
  autoCancel: false
  branches:
    include:
    - master
trigger:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: Maven
    type: GitHub 
    endpoint: KIRTHISHKT
    name: KIRTHISHKT/Maven
    ref: refs/heads/master 
    trigger: none
